In [1]:
import numpy as np

In [3]:
ls ../data/

matrix
matrix_01.csv
matrix_01.csv~
matrix_01.txt
matrix_01.txt~
matrix_02.txt
matrix_03.txt
score_record_2017_MF_final_analysis.txt*


## Numpy

In [5]:
import numpy as np
print(np.__version__)
print(np.__file__)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3) → 2행 3열
print(arr.ndim)    # 차원 수 → 2
print(arr.size)    # 전체 원소 개수 → 6
print(arr.dtype)   # 데이터 타입 → int64 (환경에 따라 다름)
print(arr.flatten())
print(arr.flatten().sum())

1.26.4
/Users/youngung/.pyenv/versions/3.12.2/lib/python3.12/site-packages/numpy/__init__.py
(2, 3)
2
6
int64
[1 2 3 4 5 6]
21


In [9]:
arr.flatten().sum()

21

In [ ]:
print(arr)
#print(arr[1::,1::])
#print(arr[::2,::2])
print(arr[::-1,::-1])
print(arr[::-1,::])
print(arr[::,::-1])

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
dotprod=0.
for i in range(len(a)):
    dotprod+=a[i]*b[i]
print(dotprod)
dotprod=(a*b).sum()
print(dotprod)

32.0
32
