In [ ]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2,3,1,9
A[1,:]=1,-1,1,1
A[2,:]=3,11,5,35
print(A)

B=A.copy() ## copy to temporary matrix B.
A[::]=0.
A[0,:] = B[2,:] # 3rd row
A[1,:] = B[0,:] # 1st row
A[2,:] = B[1,:] # 2nd row
print(A)

[[ 2.  3.  1.  9.]
 [-1. -1.  1.  1.]
 [ 3. 11.  5. 35.]]
[[ 3. 11.  5. 35.]
 [ 2.  3.  1.  9.]
 [-1. -1.  1.  1.]]


In [72]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2,3,1,9
A[1,:]=1,-1,1,1
A[2,:]=3,11,5,35
print(A)

icol=0 # 첫번째 columum
# print(A[:,icol]) ##을 순차로 정렬
a=A[:,icol] ##
print('|a|: ',a)
ind=np.argsort(a)
ind=ind[::-1] ## reverse order
print(a[ind])
A=A[ind,:]
print('A:',A)

irow=2
A[irow,:]=A[irow,:]-(A[irow,icol]/A[0,icol]) * A[0,:]
print('A:',A)

[[ 2.  3.  1.  9.]
 [ 1. -1.  1.  1.]
 [ 3. 11.  5. 35.]]
|a|:  [2. 1. 3.]
[3. 2. 1.]
A: [[ 3. 11.  5. 35.]
 [ 2.  3.  1.  9.]
 [ 1. -1.  1.  1.]]
A: [[  3.          11.           5.          35.        ]
 [  2.           3.           1.           9.        ]
 [  0.          -4.66666667  -0.66666667 -10.66666667]]
