In [2]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2,3,1,9
A[1,:]=1,-1,1,1
A[2,:]=3,11,5,35
print(A)

B=A.copy() ## copy to temporary matrix B.
A[::]=0.
A[0,:] = B[2,:] # 3rd row
A[1,:] = B[0,:] # 1st row
A[2,:] = B[1,:] # 2nd row
print(A)

[[ 2.  3.  1.  9.]
 [ 1. -1.  1.  1.]
 [ 3. 11.  5. 35.]]
[[ 3. 11.  5. 35.]
 [ 2.  3.  1.  9.]
 [ 1. -1.  1.  1.]]


In [96]:
def show(A):
    print('--')
    for i, As in enumerate(A):
        cr=''
        for j, a in enumerate(As):
            cr=f'{cr} %+8.2f'%a
        print(cr)


In [ ]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2,3,1,9
A[1,:]=1,-1,1,1
A[2,:]=3,11,5,35
#print(A)

A=np.zeros((4,5))
# filling up the matrix.
A[0,:]=2,3,1,9,-1
A[1,:]=-1,-1,-1,1,10
A[2,:]=3,3,-5,35,0
A[3,:]=3,4,10,3,-3
Aori=A.copy()
show(A)

icol=0 # 첫번째 columum

for icol in range(0,A.shape[0]-1):
    a=np.abs(A[icol:,icol]) ## Based on [absolute values] of a portion of column
    ind=np.argsort(a)
    ind=ind[::-1] # reverse order
    A[icol:,:]=A[icol:,:][ind,:]
    for irow in range(icol+1,A.shape[0]):
        A[irow,:]=A[irow,:]-A[irow,icol]/A[icol,icol]*A[icol,:]
        #print(A)

show(A)
# now one could 'diagonalize'
for icol in range(A.shape[0]-1,0,-1):
    for irow in range(0,icol):
        f=A[irow,icol]/A[icol,icol]
        A[irow,:]=A[irow,:]-f*A[icol,:]
show(A)
for icol in range(A.shape[0]):
    A[icol,:]=A[icol,:]/A[icol,icol]
show(A)
## comparison
print('Solution from Gauss elimination:',A[:,-1])
n=A.shape[0]
root=np.linalg.inv(A[:n,:n])@A[:,n]
print('Solution from np.linalg        :',root)

--
    +2.00    +3.00    +1.00    +9.00    -1.00
    -1.00    -1.00    -1.00    +1.00   +10.00
    +3.00    +3.00    -5.00   +35.00    +0.00
    +3.00    +4.00   +10.00    +3.00    -3.00
--
    +3.00    +4.00   +10.00    +3.00    -3.00
    +0.00    -1.00   -15.00   +32.00    +3.00
    +0.00    +0.00   -10.67   +17.67    +2.00
    +0.00    +0.00    +0.00    +8.25    +9.50
--
    +3.00    +0.00    +0.00    +0.00   -55.86
    +0.00    -1.00    +0.00    +0.00    -8.05
    +0.00    +0.00   -10.67    +0.00   -18.34
    +0.00    +0.00    +0.00    +8.25    +9.50
--
    +1.00    +0.00    +0.00    +0.00   -18.62
    -0.00    +1.00    -0.00    -0.00    +8.05
    -0.00    -0.00    +1.00    -0.00    +1.72
    +0.00    +0.00    +0.00    +1.00    +1.15
Solution from Gauss elimination: [-18.62121212   8.0530303    1.71969697   1.15151515]
Solution from np.linalg        : [-18.62121212   8.0530303    1.71969697   1.15151515]
