In [15]:
def show(A,fmt='%+7.2f'):
    """
    Function to more neatly print out the matrix.
    """
    print('--')
    for i, As in enumerate(A):
        cr=''
        for j, a in enumerate(As):
            cr=f'{cr} {fmt}'%a
        print(cr)


In [17]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2,3,1,9
A[1,:]=1,-1,1,1
A[2,:]=3,11,5,35
show(A)#,fmt='%7.2f')

B=A.copy() ## copy to temporary matrix B.
A[::]=0.
A[0,:] = B[2,:] # 3rd row
A[1,:] = B[0,:] # 1st row
A[2,:] = B[1,:] # 2nd row
print(A)

--
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00
   +3.00  +11.00   +5.00  +35.00
[[ 3. 11.  5. 35.]
 [ 2.  3.  1.  9.]
 [ 1. -1.  1.  1.]]


# Step by step instruction

In [ ]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2, 3, 1, 9 #irow=0
A[1,:]=1,-1, 1, 1 #irow=1
A[2,:]=3,11, 5,35 #irow=2
show(A)

B=A.copy() ## copy to temporary matrix B.
A[::]=0.
A[0,:] = B[2,:] # 3rd row [3,11,5,35] -> 1st row
A[1,:] = B[0,:] # 1st row [2, 3, 1,9] -> 2nd row
A[2,:] = B[1,:] # 2nd row [1,-1,1,1] -> 3rd row
show(A)

--
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00
   +3.00  +11.00   +5.00  +35.00
--
   +3.00  +11.00   +5.00  +35.00
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00


- np.argsosrt 활용해서 순서를 

In [ ]:
import numpy as np
# initial empty A.
A=np.zeros((3,4))
# filling up the matrix.
A[0,:]=2, 3, 1, 9 #irow=0
A[1,:]=1,-1, 1, 1 #irow=1
A[2,:]=3,11, 5,35 #irow=2
show(A)
print(np.abs(A[:,0]))
ind=np.argsort(np.abs(A[:,0]))
print(ind)
print(A[ind,0])
show(A[ind,:]) #낮은 값의 순서대로 랭크가 바뀐 것을 확인 가능
A=A[ind[::-1],:] #높은 값부터 낮은 값 순서대로... ind[::-1] 활용
show(A)

for irow in range(1,3):
    A[irow,:]=A[0,:]-(A[0,0]/A[irow,0])*A[irow,:]
show(A)
"""
A[1,:]=A[0,:]-(A[0,0]/A[1,0])*A[1,:]
show(A)
A[2,:]=A[0,:]-(A[0,0]/A[2,0])*A[2,:]
show(A)
"""

#B=A.copy() ## copy to temporary matrix B.
#A[::]=0.
#A[0,:] = B[2,:] # 3rd row [3,11,5,35] -> 1st row
#A[1,:] = B[0,:] # 1st row [2, 3, 1,9] -> 2nd row
#A[2,:] = B[1,:] # 2nd row [1,-1,1,1] -> 3rd row
#show(A)


--
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00
   +3.00  +11.00   +5.00  +35.00
[2. 1. 3.]
[1 0 2]
[1. 2. 3.]
--
   +1.00   -1.00   +1.00   +1.00
   +2.00   +3.00   +1.00   +9.00
   +3.00  +11.00   +5.00  +35.00
--
   +3.00  +11.00   +5.00  +35.00
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00
--
   +3.00  +11.00   +5.00  +35.00
   +0.00   +6.50   +3.50  +21.50
   +0.00  +14.00   +2.00  +32.00


'\nA[1,:]=A[0,:]-(A[0,0]/A[1,0])*A[1,:]\nshow(A)\nA[2,:]=A[0,:]-(A[0,0]/A[2,0])*A[2,:]\nshow(A)\n'

In [60]:
import numpy as np
# initial empty A.
if False:
    A=np.zeros((3,4))
    # filling up the matrix.
    A[0,:]=2, 3, 1, 9 #1st row, irow=0
    A[1,:]=1,-1, 1, 1 #2nd row, irow=1
    A[2,:]=3,11, 5,35 #3rd row, irow=2
    show(A)
else:
    A=np.zeros((4,5))
    # filling up the matrix.
    A[0,:]=2,3,1,9,-1
    A[1,:]=-1,-1,-1,1,10
    A[2,:]=3,3,-5,35,0
    A[3,:]=3,4,10,3,-3

#B=A.copy() ## copy to a temp matrix, and named it `B`
#A[::]=0.   ## zeroed.
#A[0,:] = B[2,:] # 3rd row [3,11,5,35] -> 1st row
#A[1,:] = B[0,:] # 1st row [2, 3, 1,9] -> 2nd row
#A[2,:] = B[1,:] # 2nd row [1,-1, 1,1] -> 3rd row

# swap
ind = np.argsort(np.abs(A[:,0]))
A=A[ind[::-1],:]
show(A)

for irow in range(1,A.shape[0]):
    A[irow,:]=A[0,:]-(A[0,0]/A[irow,0])*A[irow,:]
show(A)

# swap
ind = np.argsort(np.abs(A[1:,1]))
A[1:,]=A[1:,][ind[::-1],:]
show(A)

icol=1 # A:2
irow=2 # A3:
A[irow,:]=A[icol,:]-(A[icol,icol]/A[irow,icol])*A[irow,:]
show(A)


--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +3.00   +3.00   -5.00  +35.00   +0.00
   +2.00   +3.00   +1.00   +9.00   -1.00
   -1.00   -1.00   -1.00   +1.00  +10.00
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00  +15.00  -32.00   -3.00
   +0.00   -0.50   +8.50  -10.50   -1.50
   +0.00   +1.00   +7.00   +6.00  +27.00
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00   +7.00   +6.00  +27.00
   +0.00   +1.00  +15.00  -32.00   -3.00
   +0.00   -0.50   +8.50  -10.50   -1.50
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00   +7.00   +6.00  +27.00
   +0.00   +0.00   -8.00  +38.00  +30.00
   +0.00   -0.50   +8.50  -10.50   -1.50


In [ ]:
A=np.zeros((4,5))
# filling up the matrix.
A[0,:]=2,3,1,9,-1
A[1,:]=-1,-1,-1,1,10
A[2,:]=3,3,-5,35,0
A[3,:]=3,4,10,3,-3


# swap
icol=0 # A:2
ind = np.argsort(np.abs(A[icol:,icol]))
A=A[ind[::-1],:]
show(A)

for irow in range(icol+1,A.shape[0]):
    A[irow,:]=A[icol,:]-(A[icol,icol]/A[irow,icol])*A[irow,:]
show(A)

# swap
icol=1 # A:2
ind = np.argsort(np.abs(A[icol:,icol]))
A[icol:,]=A[icol:,][ind[::-1],:]
show(A)

for irow in range(icol+1,A.shape[0]):
    A[irow,:]=A[icol,:]-(A[icol,icol]/A[irow,icol])*A[irow,:]
show(A)

--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +3.00   +3.00   -5.00  +35.00   +0.00
   +2.00   +3.00   +1.00   +9.00   -1.00
   -1.00   -1.00   -1.00   +1.00  +10.00
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00  +15.00  -32.00   -3.00
   +0.00   -0.50   +8.50  -10.50   -1.50
   +0.00   +1.00   +7.00   +6.00  +27.00
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00   +7.00   +6.00  +27.00
   +0.00   +1.00  +15.00  -32.00   -3.00
   +0.00   -0.50   +8.50  -10.50   -1.50
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   +1.00   +7.00   +6.00  +27.00
   +0.00   +0.00   -8.00  +38.00  +30.00
   +0.00   +0.00  +24.00  -15.00  +24.00


## Combination of swap & forward

In [ ]:
if True:
    A=np.zeros((3,4))
    # filling up the matrix.
    A[0,:]=2, 3, 1, 9 #irow=0
    A[1,:]=1,-1, 1, 1 #irow=1
    A[2,:]=3,11, 5,35 #irow=2
else:
    A=np.zeros((4,5))
    # filling up the matrix.
    A[0,:]=2,3,1,9,-1
    A[1,:]=-1,-1,-1,1,10
    A[2,:]=3,3,-5,35,0
    A[3,:]=3,4,10,3,-3

for icol in range(0,A.shape[0]-1):
    ## swap
    a=np.abs(A[icol:,icol]) ## Based on [absolute values] of a portion of column
    ind=np.argsort(a)
    ind=ind[::-1] # reverse order
    A[icol:,:]=A[icol:,:][ind,:]
    show(A)
    ## forward
    for irow in range(icol+1,A.shape[0]):
        A[irow,:]=A[irow,:]-A[irow,icol]/A[icol,icol]*A[icol,:]
    show(A)
    print('****************')


--
   +3.00  +11.00   +5.00  +35.00
   +2.00   +3.00   +1.00   +9.00
   +1.00   -1.00   +1.00   +1.00
--
   +3.00  +11.00   +5.00  +35.00
   +0.00   -4.33   -2.33  -14.33
   +0.00   -4.67   -0.67  -10.67
****************
--
   +3.00  +11.00   +5.00  +35.00
   +0.00   -4.67   -0.67  -10.67
   +0.00   -4.33   -2.33  -14.33
--
   +3.00  +11.00   +5.00  +35.00
   +0.00   -4.67   -0.67  -10.67
   +0.00   +0.00   -1.71   -4.43
****************


# A systematic solution

In [110]:
import numpy as np
# initial empty A.
if False:
    A=np.zeros((3,4))
    # filling up the matrix.
    A[0,:]=2,3,91,9
    A[1,:]=11,-1,1,1
    A[2,:]=3,11,5,35
    #print(A)
elif False:
    A=np.zeros((3,4))
    # filling up the matrix.
    A[0,:]=1,1,1,2
    A[1,:]=1,1,1,3
    A[2,:]=1,2,3,4
    #print(A)
else:
    A=np.zeros((4,5))
    # filling up the matrix.
    A[0,:]=2,3,1,9,-1
    A[1,:]=-1,-1,-1,1,10
    A[2,:]=3,3,-5,35,0
    A[3,:]=3,4,10,3,-3

Aori=A.copy()
n=A.shape[0]
print('det:',np.linalg.det(A[:,:n]))
show(A)


icol=0 # 첫번째 columum

for icol in range(0,A.shape[0]-1):
    a=np.abs(A[icol:,icol]) ## Based on [absolute values] of a portion of column
    ind=np.argsort(a)
    ind=ind[::-1] # reverse order
    A[icol:,:]=A[icol:,:][ind,:]
    for irow in range(icol+1,A.shape[0]):
        A[irow,:]=A[irow,:]-A[irow,icol]/A[icol,icol]*A[icol,:]
        #print(A)

show(A)
# now one could 'diagonalize'
for icol in range(A.shape[0]-1,0,-1):
    for irow in range(0,icol):
        f=A[irow,icol]/A[icol,icol]
        A[irow,:]=A[irow,:]-f*A[icol,:]
show(A)
for icol in range(A.shape[0]):
    A[icol,:]=A[icol,:]/A[icol,icol]
show(A)
## comparison

print('Solution from Gauss elimination:',A[:,-1])
n=A.shape[0]
root=np.linalg.inv(A[:,:n])@A[:,n]
print('Solution from np.linalg.inv    :',root)
print('Solution from np.linalg.solve  :',np.linalg.solve(A[:,:n], A[:,n]))

det: -263.99999999999994
--
   +2.00   +3.00   +1.00   +9.00   -1.00
   -1.00   -1.00   -1.00   +1.00  +10.00
   +3.00   +3.00   -5.00  +35.00   +0.00
   +3.00   +4.00  +10.00   +3.00   -3.00
--
   +3.00   +4.00  +10.00   +3.00   -3.00
   +0.00   -1.00  -15.00  +32.00   +3.00
   +0.00   +0.00  -10.67  +17.67   +2.00
   +0.00   +0.00   +0.00   +8.25   +9.50
--
   +3.00   +0.00   +0.00   +0.00  -55.86
   +0.00   -1.00   +0.00   +0.00   -8.05
   +0.00   +0.00  -10.67   +0.00  -18.34
   +0.00   +0.00   +0.00   +8.25   +9.50
--
   +1.00   +0.00   +0.00   +0.00  -18.62
   -0.00   +1.00   -0.00   -0.00   +8.05
   -0.00   -0.00   +1.00   -0.00   +1.72
   +0.00   +0.00   +0.00   +1.00   +1.15
Solution from Gauss elimination: [-18.62121212   8.0530303    1.71969697   1.15151515]
Solution from np.linalg.inv    : [-18.62121212   8.0530303    1.71969697   1.15151515]
Solution from np.linalg.solve  : [-18.62121212   8.0530303    1.71969697   1.15151515]
