# Notebook to help understanding of stress tensor

- Mayavi is used to create 3D visualization of body under force

In [1]:
%gui qt

In [2]:
#%pylab inline

In [3]:
import mayavi

In [5]:
import mayavi.mlab

In [6]:
import mayavi.mlab as mlab

In [11]:
from numpy import pi, sin, cos, mgrid
import numpy as np

In [12]:
def p2cart(p,t,r):
    x=r*np.cos(p)*np.sin(t)
    y=r*np.sin(p)*np.sin(t)
    z=r*np.cos(t)
    return x,y,z

def p2carta(p,t,r):
    p=p*np.pi/180.
    t=t*np.pi/180.
    x=r*np.cos(p)*np.sin(t)
    y=r*np.sin(p)*np.sin(t)
    z=r*np.cos(t)
    return x,y,z

def c2cart(r,p,z):
    x=r*cos(p)
    y=r*sin(p)
    return x,y,z

def c2carta(r,p,z):
    p=p*np.pi/180.
    x=r*cos(p)
    y=r*sin(p)
    return x,y,z

In [75]:
def rot(th,ph):
    th=th*np.pi/180.
    ph=ph*np.pi/180.
    a=np.zeros((3,3))
    b=np.zeros((3,3))
    
    a[0,0]=cos(th)
    a[0,1]=sin(th)
    a[1,0]=-sin(th)
    a[1,1]=cos(th)
    a[2,2]=1.
    
    b[0,0]=cos(ph)
    b[0,2]=sin(ph)
    b[1,1]=1.
    b[2,0]=-sin(ph)    
    b[2,2]=cos(ph)
    print(a)
    print(b)
    return np.dot(a,b)

In [77]:
rot(45,45)

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


array([[ 0.5       ,  0.70710678,  0.5       ],
       [-0.5       ,  0.70710678, -0.5       ],
       [-0.70710678,  0.        ,  0.70710678]])

In [79]:
fig=mlab.figure(figure=1)
mlab.clf(fig)

#mlab.outline()
#mlab.colorbar()
#mlab.axes()
v=mlab.view()
mlab.view(*v)

## full circle
[phi,theta] = mgrid[0:2*np.pi:30j, 0:np.pi:30j]
x,y,z=p2cart(phi,theta,1)
s_full_circle = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,1,1),opacity=0.5,#representation='points',#'fancymesh'
             )
mlab.axes()
## define n vector


## x,y,z axes
n_sphe=[0,90,1]
n_cart=p2carta(*n_sphe)
ori=[0,0,0]
mlab.quiver3d(*ori,*n_cart,scale_factor=1,color=(1,0,0),mode='arrow')
mlab.view(*v)
n_sphe=[90,90,1]
n_cart=p2carta(*n_sphe)
ori=[0,0,0]
mlab.quiver3d(*ori,*n_cart,scale_factor=1,color=(0,1,0),mode='arrow')
mlab.view(*v)
n_sphe=[0,0,1]
n_cart=p2carta(*n_sphe)
ori=[0,0,0]
s=mlab.quiver3d(*ori,*n_cart,scale_factor=1,color=(0,0,1),mode='arrow')
mlab.view(*v)




(63.88938412374597,
 65.5756985945873,
 9.621333996549108,
 array([0.00366002, 0.00146551, 0.        ]))

In [18]:
fig=mlab.figure(figure=1)
mlab.clf(fig)

#mlab.outline()
#mlab.colorbar()
#mlab.axes()


## full circle
[phi,theta] = mgrid[0:2*np.pi:30j, 0:np.pi:30j]
x,y,z=p2cart(phi,theta,1)
s1 = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,1,1),opacity=1,#representation='points',#'fancymesh'
             )
s2 = mlab.mesh(x, y, z+1,
              figure=fig,
              color=(1,1,1),opacity=1,#representation='points',#'fancymesh'
             )




v=mlab.view()
roll=mlab.roll()
#mlab.savefig('/tmp/0.png')
mlab.clf()
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,1,1),opacity=1,#representation='points',#'fancymesh'
             )
mlab.view(*v)
mlab.roll(roll)
#mlab.outline()



# - arrow that represents the external force
## quiver
ph=20;th=100.
[phi,theta] = mgrid[ph:ph:1j, th:th:1j]
x,y,z=p2carta(ph,th,1)
mlab.quiver3d(x,y,z,x+0.1,y+0.1,z+0.1,scale_factor=1,color=(0,0,0),mode='arrow',resolution=30)
mlab.view(*v)

ph=230;th=50.
[phi,theta] = mgrid[ph:ph:1j, th:th:1j]
x,y,z=p2carta(ph,th,1)
mlab.quiver3d(x,y,z,x+0.1,y+0.1,z+0.1,scale_factor=1,color=(0,0,0),mode='arrow',resolution=30)

ph=120;th=90.
[phi,theta] = mgrid[ph:ph:1j, th:th:1j]
x,y,z=p2carta(ph,th,1)
mlab.quiver3d(x,y,z,x+0.1,y+0.3,z+0.1,scale_factor=1,color=(0,0,0),mode='arrow',resolution=30)


mlab.view(*v)
mlab.savefig('/tmp/1.png')
mlab.clf(fig)








## semi sphere
[phi,theta] = mgrid[0:2*np.pi:30j, np.pi/2.:np.pi:30j]
x,y,z=p2cart(phi,theta,1)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,1,1),opacity=0.1,#representation='points',#'fancymesh'
             )
#mlab.axes()
## cross section
[r,theta] = mgrid[0:1:30j, -np.pi:np.pi:30j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,0.8,0.8),opacity=0.90#,representation='wireframe'#representation='points',#'fancymesh'
             )







## the other part of sphere-cut
[phi,theta] = mgrid[0:2*np.pi:30j, 0:np.pi/2:30j]
x,y,z=p2cart(phi,theta,1)
s = mlab.mesh(x, y, z+1,
              figure=fig,
              color=(1,1,1),opacity=1,#representation='points',#'fancymesh'
             )
## cross section
[r,theta] = mgrid[0:1:30j, -np.pi:np.pi:30j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
s = mlab.mesh(x, y, z+1,
              figure=fig,
              color=(1,0.8,0.8),opacity=0.90#,representation='wireframe'#representation='points',#'fancymesh'
             )

mlab.view(*v)
mlab.roll(roll)
mlab.savefig('/tmp/2.png')



### force distribution
[r,theta] = mgrid[0:1:5j, -np.pi:np.pi:18j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
zeros=x.copy()
zeros[::]=0
unit=zeros.copy()
unit[::]=1.

f3=np.sqrt(y**2+x**2)*0.2
f2=sin(np.arctan2(y,x))*0.2
f1=zeros
mlab.quiver3d(x,y,z,f1,f2,f3,scale_factor=1.0)
mlab.quiver3d(x,y,z+1,-f1,-f2,-f3,scale_factor=1.0)
mlab.savefig('/tmp/3.png')
mlab.clf(fig)



## coupled force
## cross section
[r,theta] = mgrid[0:1:30j, -np.pi:np.pi:30j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,0.8,0.8)#,representation='wireframe'#representation='points',#'fancymesh'
             )

### force distribution
[r,theta] = mgrid[0:1:10j, -np.pi:np.pi:30j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
zeros=x.copy()
zeros[::]=0
unit=zeros.copy()
unit[::]=1.

f3=np.sqrt(y**2+x**2)*0.2
f2=sin(np.arctan2(y,x))*0.2
f1=zeros
mlab.quiver3d(x,y,z,f1,f2,f3,scale_factor=1.0)
mlab.quiver3d(x,y,z,-f1,-f2,-f3,scale_factor=1.0)
mlab.view(*v)
mlab.roll(roll)
mlab.savefig('/tmp/4.png')
mlab.clf(fig)




## coupled force
## cross section
[r,theta] = mgrid[0:1:60j, -np.pi:np.pi:360j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,0.8,0.8)#,representation='wireframe'#representation='points',#'fancymesh'
             )

### force distribution
[r,theta] = mgrid[0:1:60j, -np.pi:np.pi:360j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
zeros=x.copy()
zeros[::]=0
unit=zeros.copy()
unit[::]=1.

f3=np.sqrt(y**2+x**2)*0.2
f2=sin(np.arctan2(y,x))*0.2
f1=zeros
mlab.quiver3d(x,y,z,f1,f2,f3,scale_factor=1.0,opacity=0.9)
mlab.quiver3d(x,y,z,-f1,-f2,-f3,scale_factor=1.0,opacity=0.9)
mlab.view(*v)
mlab.roll(roll)
mlab.savefig('/tmp/5.png')
mlab.clf(fig)






## coupled force
## cross section
rs=np.linspace(0.2,0.0001,5)
for i in range(len(rs)):
    [r,theta] = mgrid[0:rs[i]:60j, -np.pi:np.pi:360j]
    z=r.copy()
    z[::]=0
    x,y,z=c2cart(r,theta,z)
    x=x+0.5
    y=y-0.2
    s = mlab.mesh(x, y, z,
                  figure=fig,
                  color=(1,0.8,0.8)#,representation='wireframe'#representation='points',#'fancymesh'
                 )

    ### force distribution
    f3=np.sqrt(y**2+x**2)*0.2
    f2=sin(np.arctan2(y,x))*0.2
    f1=zeros
    mlab.quiver3d(x,y,z,f1,f2,f3,scale_factor=1.0,opacity=0.9)
    mlab.quiver3d(x,y,z,-f1,-f2,-f3,scale_factor=1.0,opacity=0.9)
    mlab.view(*v)
    mlab.roll(roll)
    mlab.savefig('/tmp/%i.png'%(i+6))
    if i<len(rs)-1:mlab.clf(fig)


        
        
        
## semi sphere
[phi,theta] = mgrid[0:2*np.pi:30j, np.pi/2.:np.pi:30j]
x,y,z=p2cart(phi,theta,1)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,1,1),opacity=0.1,#representation='points',#'fancymesh'
             )

mlab.axes()
#mlab.outline()
## cross section
[r,theta] = mgrid[0:1:30j, -np.pi:np.pi:30j]
z=r.copy()
z[::]=0
x,y,z=c2cart(r,theta,z)
s = mlab.mesh(x, y, z,
              figure=fig,
              color=(1,0.8,0.8),opacity=0.90#,representation='wireframe'#representation='points',#'fancymesh'
             )

mlab.view(*v)
mlab.roll(roll)


[r,theta] = mgrid[0:rs[i]:60j, -np.pi:np.pi:360j]
z=r.copy()
z[::]=0.3
x,y,z=c2cart(r,theta,z)
x=x+0.5
y=y-0.2
mlab.points3d(x,y,z,color=(0,0,0))
#mlab.plot3d(x,y,z,color=(0,0,0))
mlab.view(*v)
mlab.roll(roll) 
mlab.savefig('/tmp/%i_fin.png'%(i+7))