In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Suppose that we have a local constitutive law such that
$$
\varepsilon^{el}=M^{el}:\sigma
$$
for each individual grains.

In [3]:
inv=np.linalg.inv

-- Transformation rules for (2x1) matrix and (2x2) matrix.

In [4]:
def trans_2d_vec(a,r):
    b=np.zeros(2)
    for i in range(2):
        for j in range(2):
            b[i]=b[i]+r[i,j]*a[j]
    return b
def trans_2d_ten(a,r):
    b=np.zeros((2,2))
    for i in range(2):
        for j in range(2):
            for k in range(2):
                for l in range(2):
                    b[i,j]=b[i,j]+r[i,k]*r[j,l]*a[k,l]
    return b

In [5]:
ngr=3
weights=np.zeros(ngr)
weights[::]=1./ngr

In [6]:
thetas=[0,45,90]
thetas=np.array(thetas)*np.pi/180. ## to radian
R=np.zeros((2,2,len(thetas)))

for i in range(len(thetas)):
    r=np.zeros((2,2))
    r[0,0]=cos(thetas[i])
    r[0,1]=-sin(thetas[i])
    r[1,0]=sin(thetas[i])
    r[1,1]=cos(thetas[i])
    R[:,:,i]=r[:,:]

- Local elastic modulus

In [7]:
c=np.zeros((2,2))
c[0,0]=200000
c[1,1]=100000

In [8]:
print ('c:',c)

c: [[200000.      0.]
 [     0. 100000.]]


## let's calculate the moduli in the lab axes coordinates

In [9]:
cgr=np.zeros((2,2,ngr))

In [10]:
for igr in range(ngr):
    r=R[:,:,igr]
    dum=trans_2d_ten(c,r)
    print('dum:',dum)
    cgr[:,:,igr]=dum

dum: [[200000.      0.]
 [     0. 100000.]]
dum: [[150000.  50000.]
 [ 50000. 150000.]]
dum: [[1.000000e+05 6.123234e-12]
 [6.123234e-12 2.000000e+05]]


In [11]:
print('cgr:',cgr.T)

cgr: [[[2.000000e+05 0.000000e+00]
  [0.000000e+00 1.000000e+05]]

 [[1.500000e+05 5.000000e+04]
  [5.000000e+04 1.500000e+05]]

 [[1.000000e+05 6.123234e-12]
  [6.123234e-12 2.000000e+05]]]


- weighted average of elastic stiffness

In [12]:
cav=np.zeros((2,2))
for igr in range(ngr):
    cav[:,:]=cav[:,:]+cgr[:,:,igr]*weights[igr]

In [19]:
print(cav/1000)

[[150.          16.66666667]
 [ 16.66666667 150.        ]]


In [21]:
inv(cav/1000)

array([[ 0.00675, -0.00075],
       [-0.00075,  0.00675]])

In [23]:
cav/1000

array([[150.        ,  16.66666667],
       [ 16.66666667, 150.        ]])